# Generated by Django 5.0.4 on 2024-04-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('ec_id', models.AutoField(primary_key=True, serialize=False)),
                ('ec_pregunta_1', models.IntegerField()),
                ('ec_pregunta_2', models.IntegerField()),
                ('ec_pregunta_3', models.IntegerField()),
                ('ec_pregunta_4', models.IntegerField()),
                ('ec_pregunta_5', models.IntegerField()),
                ('ec_pregunta_6', models.IntegerField()),
                ('ec_pregunta_7', models.IntegerField()),
                ('ec_pregunta_8', models.IntegerField()),
                ('ec_pregunta_9', models.IntegerField()),
                ('ec_pregunta_10', models.IntegerField()),
                ('ec_pregunta_11', models.IntegerField()),
                ('ec_pregunta_12', models.IntegerField()),
                ('ec_pregunta_13', models.IntegerField()),
                ('ec_pregunta_14', models.IntegerField()),
            ],
            options={
                'db_table': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('sen_id', models.AutoField(primary_key=True, serialize=False)),
                ('sen_emg', models.IntegerField()),
                ('sen_temperatura', models.IntegerField()),
                ('sen_freq_respiratoria', models.IntegerField()),
                ('sen_freq_cardiaca', models.IntegerField()),
            ],
            options={
                'db_table': 'sensores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_edad', models.IntegerField()),
                ('usr_peso', models.FloatField()),
                ('usr_altura', models.FloatField()),
                ('usr_genero', models.CharField(max_length=10)),
                ('usr_facultad', models.CharField(max_length=50)),
                ('usr_vive_solo', models.SmallIntegerField(null=True)),
                ('usr_trabaja', models.SmallIntegerField(null=True)),
                ('usr_hijos', models.SmallIntegerField(null=True)),
                ('ec_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='detecion_estres.encuesta')),
                ('sen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='detecion_estres.sensores')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
