# Generated by Django 5.0.4 on 2024-04-20 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecion_estres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ec_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sen_id',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detecion_estres.usuario'),
        ),
        migrations.AddField(
            model_name='sensores',
            name='usr',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='detecion_estres.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usr_genero',
            field=models.CharField(max_length=20),
        ),
    ]
