# Generated by Django 5.0 on 2024-04-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecion_estres', '0002_remove_usuario_ec_id_remove_usuario_sen_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usr_estres',
            field=models.SmallIntegerField(null=True),
        ),
    ]
