# Generated by Django 5.0.4 on 2024-05-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecion_estres', '0003_usuario_usr_estres'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='ec_total',
            field=models.IntegerField(null=True),
        ),
    ]
