# Generated by Django 5.0.4 on 2024-05-31 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecion_estres', '0004_encuesta_ec_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detecion_estres.usuario'),
        ),
    ]
