# Generated by Django 5.0.4 on 2024-07-16 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detecion_estres', '0005_alter_sensores_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensores',
            name='sen_emg',
        ),
    ]
