# Generated by Django 5.0.4 on 2024-08-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecion_estres', '0006_remove_sensores_sen_emg'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usr_estresPuntos',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usr_estresPuntos_texto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
