# Generated by Django 5.0.4 on 2024-08-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecion_estres', '0007_usuario_usr_estrespuntos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usr_estresPuntos_texto',
            new_name='usr_estresTexto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usr_estres',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usr_estresPorcentaje',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usr_estresPuntos',
            field=models.SmallIntegerField(null=True),
        ),
    ]
