# Generated by Django 5.0.4 on 2024-08-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detecion_estres', '0008_rename_usr_estrespuntos_texto_usuario_usr_estrestexto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usr_estresPorcentaje',
            new_name='usr_estres_porcentaje',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usr_estresPuntos',
            new_name='usr_estres_puntos',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usr_estresTexto',
            new_name='usr_estres_texto',
        ),
    ]
